# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


答： np.zeros會初始化陣列的元素值為0，而np.empty不會，陣列元素值是隨機的。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
import numpy as np

a = np.random.rand(2, 3) * 100
a

array([[36.3094011 , 34.88526549, 94.62584414],
       [67.57089751, 95.40939943, 20.3330443 ]])

In [2]:
a.astype('int')

array([[36, 34, 94],
       [67, 95, 20]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [3]:
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m)
b = a

# 取整數之方式一：截去小數
print((a - b % 1) + m)
# 取整數之方式二：使用astype()
print((a + m).astype('int'))

[[21. 35. 35.]
 [23. 23. 32.]]
[[21 35 35]
 [23 23 32]]
